### ISSUE TITLE
link brocken

### ISSUE THREAD

**Issue by Mair** [giltal/NES_EMU_ESP32#1]
Hi,
You reference https://github.com/giltal/libraries in the read me but its a Brocken link

**Comment by giltal** [comment]
Fixed :-)

**Comment by Mair** [comment]
Thanks for the quick response. Unfortunately the new link is also Brocken. Is it perhaps a private repo?

**Comment by giltal** [comment]
Fixed and tested :-)
On 14-Sep-22 2:29:01 PM, Mair Swartz ***@***.***> wrote:
Thanks for the quick response. Unfortunately the new link is also Brocken. Is it perhaps a private repo?

**Comment by giltal** [comment]
You are right, I hope now that it is fixed, I tried it and got the proper folder

**Comment by Mair** [comment]
Looks good. Thank you 😊
